server:
  port: 8082

spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

  application:
    name: exchange-processing

  datasource:
    url: jdbc:postgresql://localhost:5432/processing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true