spring:
  config:
    import: optional:file:.env[.properties]

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

  application:
    name: exchange-processing-service

  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/processing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${EUREKA_HOST}:8761/eureka/

service:
  currency:
    url: ${CURRENCY_URL}