cloud:
  db-host: ${DB_HOST}
  eureka-host: ${EUREKA_HOST}
  currency-url: ${CURRENCY_URL}


spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

  application:
    name: exchange-processing-service

  datasource:
    url: jdbc:postgresql://${cloud.db-host}:5432/processing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://${cloud.eureka-host}:8761/eureka/

service:
  currency:
    url: "http://${cloud.currency-url}:8085"