spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml

  application:
    name: exchange-processing-service

  datasource:
    url: jdbc:postgresql://localhost:5432/processing
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 8082

eureka:
  client:
    enabled: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

service:
  currency:
    url: "http://localhost:8085"